sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t huzaynbolt/docker-react -f Dockerfile.dev .


script:
  - docker run huzaynbolt/docker-react npm run test  --coverage