FROM node:12

# Create app directory
WORKDIR '/app'

# Install app dependencies
# A wildcard is used to ensure package.json is copied
# where available (npm@5+)
COPY package.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Default command
CMD ["npm", "run", "start"]